Add field
NdubuisiJr/TypeExtender pull request #2
Opened 2021-08-13 12:31 UTC by JindrichSusen

2021-08-13 14:55 UTC, NdubuisiJr commented
Hi @JindrichSusen 
Thanks for taking out the time to contribute to this project.

I have a few changes I would like you to implement. After which, we can merge...

2021-08-13 15:04 UTC, NdubuisiJr requested changes
Please implement the requested changes and we are good to merge

Thanks a lot

2021-08-13 15:04 UTC, NdubuisiJr commented on TypeExtender/TypeExtender/TypeExtender.cs
> +        {
For code style consistency, please implement all your code blocks with the first brace ('{') on the same line as the definition.
e.g 
```
private void addField(...) {
}
```

2021-08-13 15:04 UTC, NdubuisiJr commented on TypeExtender/TypeExtender/TypeExtender.cs
> +
Most of the public methods have a Generic overload... 

Please implement a generic overload for the AddField function.

2021-08-13 15:04 UTC, NdubuisiJr commented on TypeExtender/TypeExtender.Test/TypeExtenderShould.cs
> +
Please add a test for the generic overload requested below...

2021-08-14 10:36 UTC, JindrichSusen commented
Hi. I hope you like the changes :) Thanks

2021-08-15 08:41 UTC, NdubuisiJr commented
Looks great...

@JindrichSusen consider starring the project so that others can find it easily.

Thanks a lot.

2021-08-15 08:41 UTC, merged